server:
  port: 60007
  servlet:
    context-path: /devops

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  main:
    allow-bean-definition-overriding: true
  datasource:
    mysql-server:
      type: com.zaxxer.hikari.HikariDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://${NACOS_HOST:192.168.2.158}:3306/sunos-operate?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&allowMultiQueries=true&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
      username: root
      password: ${MYSQL_PASSWORD}
      hikari:
        minimum-idle: 1
        idle-timeout: 600000
        maximum-pool-size: 10
        auto-commit: true
        pool-name: MyHikariCP
        max-lifetime: 1800000
        connection-timeout: 30000
        connection-test-query: SELECT 1
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL55Dialect
        order_inserts: true
        order_updates: true
        generate-statistics: false
        jdbc.batch_size: 1000

  redis:
    port: 6379
    host: ${NACOS_HOST:192.168.2.158}
    password: ${REDIS_PASSWORD}
    timeout: 60s
    database: 1
    lettuce:
      pool:
        min-idle: 10
        max-idle: 100
        max-active: 200
        max-wait: 1000ms

security:
  oauth2:
    client:
      client-id: sunos-client
      client-secret: sunos-client
      access-token-uri: http://${NACOS_HOST:192.168.2.158}:60001/sauth/oauth/token
      user-authorization-uri: http://${NACOS_HOST:192.168.2.158}:60001/sauth/oauth/authorize
    resource:
      token-info-uri: http://${NACOS_HOST:192.168.2.158}:60001/sauth/oauth/check_token
