server:
  port: 60010
  servlet:
    context-path: /swebapp

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  main:
    allow-bean-definition-overriding: true
  datasource:
    #mysql 数据库配置
    mysql-server:
      type: com.zaxxer.hikari.HikariDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://${MYSQL_HOST:121.41.109.130}:3306/sunos-operate?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&allowMultiQueries=true&useSSL=false&serverTimezone=Asia/Shanghai
      username: root
      password: ${MYSQL_PASSWORD}
      hikari:
        minimum-idle: 1
        idle-timeout: 600000
        maximum-pool-size: 10
        auto-commit: true
        pool-name: MyHikariCP
        max-lifetime: 1800000
        connection-timeout: 30000
        connection-test-query: SELECT 1
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL55Dialect
        order_inserts: true
        order_updates: true
        generate_statistics: false         #生成统计信息
        jdbc.batch_size: 1000              #开启批次储存,一批次储存量为1000,如有10000条数据则储存十次

  redis:
    port: 6379
    host: ${REDIS_HOST:192.168.2.252}
    password: ${REDIS_PASSWORD}
    timeout: 60s
    database: 1
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 10
        # 连接池中的最大空闲连接
        max-idle: 100
        # 连接池的最大数据库连接数
        max-active: 200
        # #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 1000

mybatis:
  type-aliases-package: com.sunmax.together.entity
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true
    call-setters-on-nulls: true
    jdbc-type-for-null: 'null'

security:
  oauth2:
    client:
      client-id: evcos-client
      client-secret: evcos-client
      access-token-uri: http://${AUTH_HOST:47.97.219.142}:60001/oauth/token
      user-authorization-uri: http://${AUTH_HOST:47.97.219.142}:60001/oauth/authorize
    resource:
      token-info-uri: http://${AUTH_HOST:47.97.219.142}:60001/oauth/check_token

#oss配置
aliyun:
  bucketName: ${ALIYUN_OSS_BUCKET_NAME:smfilestore}
  accessKeyId: ${ALIYUN_ACCESS_KEY_ID}
  accessKeySecret: ${ALIYUN_ACCESS_KEY_SECRET}
  endpoint: ${ALIYUN_OSS_ENDPOINT:http://oss-cn-hangzhou.aliyuncs.com}

