server:
  port: 60008
  servlet:
    context-path: /configure

spring:
  application:
    name: configure-service
  main:
    allow-bean-definition-overriding: true
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_HOST:127.0.0.1}:${NACOS_PORT:8848}
        username: ${NACOS_USERNAME:nacos}
        password: ${NACOS_PASSWORD:nacos}
        namespace: ${NACOS_NAMESPACE:public}
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  resources:
    static-locations: file:${FILE_PATH:/opt/sunos/file},file:${IMAGE_PATH:/opt/sunos/image}
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST:127.0.0.1}:${MYSQL_PORT:3306}/sunos-configure?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=GMT%2B8
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD}
    type: com.zaxxer.hikari.HikariDataSource
    filters: stat,wall,config
    maxActive: 100
    initial-size: 5
    max-wait: 60000
    min-idle: 5
    time-between-eviction-runs-millis: 600000
    min-evictable-idle-time-millis: 30000
    validation-query: select 1
    test-while-idle: true
    test-on-borrow: false
    test-on-return: false
    pool-prepared-statements: false
    max-pool-prepared-statement-per-connection-size: 20
    pool-name: primarypool

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL55Dialect
        order_inserts: true
        order_updates: true
        generate_statistics: true
        jdbc.batch_size: 50

  redis:
    port: ${REDIS_PORT:6379}
    host: ${REDIS_HOST:127.0.0.1}
    password: ${REDIS_PASSWORD}
    timeout: 60s
    database: 1
    lettuce:
      pool:
        min-idle: 10
        max-idle: 100
        max-active: 200
        max-wait: 1000

mybatis:
  typeAliasesPackage: com.taosdata.jdbc.springbootdemo.domain
  call-setters-on-nulls: true
  map-underscore-to-camel-case: true

security:
  oauth2:
    client:
      client-id: sunos-client
      client-secret: ${OAUTH2_CLIENT_SECRET:sunos-client}
      access-token-uri: http://${AUTH_HOST:127.0.0.1}:${AUTH_PORT:60001}/sauth/oauth/token
      user-authorization-uri: http://${AUTH_HOST:127.0.0.1}:${AUTH_PORT:60001}/sauth/oauth/authorize
    resource:
      token-info-uri: http://${AUTH_HOST:127.0.0.1}:${AUTH_PORT:60001}/sauth/oauth/check_token  

mqtt:
  qos: 2
  timeout: 60
  keep-alive: 60
  expire: 5
  web:
    username: ${EMQX1_USERNAME:admin}
    password: ${EMQX1_PASSWORD:public}
    host-url: tcp://${EMQX1_HOST:127.0.0.1}:${EMQX1_PORT:1883}
    client-id: emqx${random.value}
    client-topic: webTopic

platform:
  id: ${PLATFORM_ID:MACQKWDXI}
  secret: ${PLATFORM_SECRET:JbhI7olOTAKs2ZNU}
  data-secret: ${PLATFORM_DATA_SECRET:RVPxJ4aiZwMxnGri}
  data-secret-iv: ${PLATFORM_DATA_SECRET_IV:kWKNeZyRYVCgYlX1}
  sig-secret: ${PLATFORM_SIG_SECRET:WRfsTnyTI4r17b55}
  interflow-url: ${PLATFORM_INTERFLOW_URL:http://1.95.55.247/api/interflow-service/interFlow/XC59EF6B6/evcs/version/}

ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
