server:
  port: 60003
  servlet:
    context-path: /device

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  main:
    allow-bean-definition-overriding: true
  #master 默认数据源
  datasource:
    model:
      type: com.zaxxer.hikari.HikariDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://${MYSQL_HOST:121.41.109.130}:13006/sunos-model?serverTimezone=GMT%2B8&autoReconnect=true&allowMultiQueries=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
      username: root
      password: ${MYSQL_PASSWORD}
    #slave 从数据源
    access:
      type: com.zaxxer.hikari.HikariDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://${MYSQL_HOST:121.41.109.130}:13006/sunos-access?serverTimezone=GMT%2B8&autoReconnect=true&allowMultiQueries=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
      username: root
      password: ${MYSQL_PASSWORD}
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL55Dialect

  redis:
    port: 6379
    host: ${MYSQL_HOST:121.41.109.130}
    password: ${REDIS_PASSWORD}
    timeout: 60s
    database: 1
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 10
        # 连接池中的最大空闲连接
        max-idle: 100
        # 连接池的最大数据库连接数
        max-active: 200
        # #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 1000

mybatis:
  type-aliases-package: com.sunmax.device.entity
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true
    call-setters-on-nulls: true
    jdbc-type-for-null: 'null'

security:
  oauth2:
    client:
      client-id: sunos-client
      client-secret: sunos-client
      access-token-uri: http://localhost:60001/sauth/oauth/token
      user-authorization-uri: http://localhost:60001/sauth/oauth/authorize
    resource:
      token-info-uri: http://localhost:60001/sauth/oauth/check_token

